### ISSUE TITLE
Fish support

### ISSUE THREAD

**Issue by istx25** [mattrajca/sudo-touchid#12]
I'm not entirely sure what this would entail but I've started using Fish instead of Bash. It'd be cool to get some instructions for this if it inherently works with Fish (just different setup instructions). :)

**Comment by qaisjp** [comment]
Have you tried it with fish?

**Comment by istx25** [comment]
Not sure how to configure it so that's why I asked for help either configuring it or asking for the support to be added if more needed to be done.

**Comment by nhooyr** [comment]
I don't think anything else would need to be done.

**Comment by 19h** [comment]
This is a drop-in replacement of sudo -- that is, if sudo works, sudo-touchid _will_ work.

**Comment by yvt** [comment]
sudo-touchid has nothing to do with a shell — Since it’s merely a standalone program, it does not matter what shell you are using. Also, you change the default shell by `chsh` and `sudo -i` would automatically use the new shell. 

I feel like this issue might as well be closed since there is nothing to be done further.
