### ISSUE TITLE
No popup when running within tmux

### ISSUE THREAD

**Issue by dadgar** [mattrajca/sudo-touchid#13]
Hey,

The pop-up for TouchID appears when running on iTerm2 but once sudo is run within a tmux session, there is no popup.

**Comment by pgib** [comment]
Are you using [reattach-to-user-namespace](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard)?

I'm running from within tmux, and it's working for me. I have this in my `~/.tmux.conf` file:

```
set-option -g default-command "reattach-to-user-namespace -l $SHELL"
```

**Comment by nksmnf** [comment]
+

**Comment by bentruyman** [comment]
If @pgib's theory is correct (I suspect it is), then @dadgar the following should also fail for you when `sudo-touchid` also fails:

```shell
$ echo 'works!' | pbcopy && pbpaste
```

This should print 'works!' on the next line.

**Comment by dadgar** [comment]
The reattach to user namespace did the trick!

**Comment by veelenga** [comment]
Suggested solution does not work for me. Even this command:

```
$ reattach-to-user-namespace sudo su
```
doesn't bring the popup.

But sudo-touchid works just perfectly without tmux. Any ideas why?

**Comment by fabianishere** [comment]
@veelenga I had the same issue where it did not work within a tmux session. These patches seem to fix it for me:
1. https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/pull/70
2. https://github.com/tmux/tmux/pull/1434

**EDIT**: Since these patches caused some technical issues (as explained in the pull requests), I instead solved the problem using a custom PAM module to reattach to the user's per-session namespace before running the `pam_tid` module: https://github.com/fabianishere/pam_reattach

**Comment by veelenga** [comment]
I can confirm applying these two patches fixes it on my side too.

**Comment by espoelstra** [comment]
@fabianishere I ❤️ you man! Hadn't even realized I didn't have TouchID for `sudo` under tmux for a couple weeks because I hadn't needed it, but when I did I was really sad typing out my sup3rLong&&SecureP@ssw0rd for the first time in a long time. I immediately searched and found all the above mentioned issues, and after a couple days with your pam module repo open and needing to `sudo` a couple more things I finally followed the directions and they were so painless the only thing that could have made it easier would be a `brew install pam_reattach` formula that depends on `cmake` and does the compile and install so I don't have to copy and paste a whole 3-4 commands one time. 😛

**Comment by fabianishere** [comment]
@espoelstra Glad you like it! I actually have a Homebrew formula already (see https://github.com/fabianishere/homebrew-core/tree/pam_reattach-1.2), but need to get it into the official repository. Since the repository is not notable enough, I think someone else needs to make the submission request.

**Comment by laurentcaille** [comment]
@fabianishere Tested and approved, you save my day!
